var annotated_dup =
[
    [ "CanvaElement", "structCanvaElement.html", "structCanvaElement" ],
    [ "CanvasDrawArcArgs", "structCanvasDrawArcArgs.html", "structCanvasDrawArcArgs" ],
    [ "CanvasDrawLineArgs", "structCanvasDrawLineArgs.html", "structCanvasDrawLineArgs" ],
    [ "CanvasDrawRectangleArgs", "structCanvasDrawRectangleArgs.html", "structCanvasDrawRectangleArgs" ],
    [ "CanvasSetFGArgs", "structCanvasSetFGArgs.html", "structCanvasSetFGArgs" ],
    [ "Character", "structCharacter.html", "structCharacter" ],
    [ "gladGLversionStruct", "structgladGLversionStruct.html", "structgladGLversionStruct" ],
    [ "GooeyBackend", "structGooeyBackend.html", "structGooeyBackend" ],
    [ "GooeyBackendContext", "structGooeyBackendContext.html", "structGooeyBackendContext" ],
    [ "GooeyButton", "structGooeyButton.html", "structGooeyButton" ],
    [ "GooeyCanvas", "structGooeyCanvas.html", "structGooeyCanvas" ],
    [ "GooeyCheckbox", "structGooeyCheckbox.html", "structGooeyCheckbox" ],
    [ "GooeyDropdown", "structGooeyDropdown.html", "structGooeyDropdown" ],
    [ "GooeyEvent", "structGooeyEvent.html", "structGooeyEvent" ],
    [ "GooeyLabel", "structGooeyLabel.html", "structGooeyLabel" ],
    [ "GooeyLayout", "structGooeyLayout.html", "structGooeyLayout" ],
    [ "GooeyMenu", "structGooeyMenu.html", "structGooeyMenu" ],
    [ "GooeyMenuChild", "structGooeyMenuChild.html", "structGooeyMenuChild" ],
    [ "GooeyRadioButton", "structGooeyRadioButton.html", "structGooeyRadioButton" ],
    [ "GooeyRadioButtonGroup", "structGooeyRadioButtonGroup.html", "structGooeyRadioButtonGroup" ],
    [ "GooeyScrollable", "structGooeyScrollable.html", "structGooeyScrollable" ],
    [ "GooeySignal", "structGooeySignal.html", "structGooeySignal" ],
    [ "GooeySignal_Slot", "structGooeySignal__Slot.html", "structGooeySignal__Slot" ],
    [ "GooeySlider", "structGooeySlider.html", "structGooeySlider" ],
    [ "GooeyTextbox", "structGooeyTextbox.html", "structGooeyTextbox" ],
    [ "GooeyTheme", "structGooeyTheme.html", "structGooeyTheme" ],
    [ "GooeyWidget", "structGooeyWidget.html", "structGooeyWidget" ],
    [ "GooeyWindow", "structGooeyWindow.html", "structGooeyWindow" ],
    [ "LogEntry", "structLogEntry.html", "structLogEntry" ],
    [ "userPtr", "structuserPtr.html", "structuserPtr" ],
    [ "Vertex", "structVertex.html", "structVertex" ]
];